---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
  releaseName: bitnami


