---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: infrastructure
  path: ./apps/overlays/production
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
