---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/overlays/development
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
