apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_template
  labels:
    app: service_template
spec:
  replicas: 1
  template:
    metadata:
      name: service_template
      labels:
        app: service_template
    spec:
      containers:
        - name: service_template
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: backend
